spring.application.name=InterviewPro
server.port=${PORT:8080}

# ===============================
# File Upload Settings
# ===============================
spring.servlet.multipart.max-file-size=3MB
spring.servlet.multipart.max-request-size=3MB



# ===============================
# Database and Spring Settings
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.org.springframework=INFO


# ===============================
# Database configuration
# ===============================
spring.jpa.database-platform=${DB_DIALECT}
spring.datasource.url=${DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}


# ===============================
# JWT Secret
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# GenAI API 
# ===============================
genKey=${GENAI_KEY}


# ===============================
# AssemblyAI API 
# ===============================
assemblyai.api.key=${ASSEMBLY_AI_KEY}


# ===============================
# OpenAI API 
# ===============================
openai.api.key=${OPEN_AI_KEY}


communication.prompt=You are an AI interviewer. Evaluate the candidate answer. Return JSON only: { "aiScore": number, "grammarScore": number, "clarityScore": number, "fluencyScore": number, "strengths": "", "weaknesses": "", "suggestions": "" }
resume.prompt=You are an advanced enterprise-grade ATS resume evaluator. Strictly analyze the resume based on industry ATS standards for the specified role. Score out of 100 using role-dependent weighted categories including contact info, summary alignment, skills relevance, education relevance, projects relevance, ATS keywords, formatting, grammar, structure and skill match. Assign zero to irrelevant sections. Give ATS optimization score separately based on parsing readiness, keyword alignment and role relevance. Return zero for both scores if resume is irrelevant to the role. Use strict scoring where 90-100 is nearly perfect and below 50 indicates major issues. Return strict raw JSON only with fields: score, atsOptimizationScore, pros, cons, suggestions.

# ===============================
# Brevo Email API 
# ===============================
brevo.api-key=${BREVO_KEY}
brevo.sender.email=${BREVO_EMAIL}
brevo.sender.name=${BREVO_NAME}
